#!/usr/bin/env python3
"""Inject a compatibility macro into the Windows CMake project.

Why: `permission_handler_windows` uses the legacy `<experimental/coroutine>`
(C++/WinRT). New MSVC turns that into an error (STL1011) and suggests
defining `_SILENCE_EXPERIMENTAL_COROUTINE_DEPRECATION_WARNINGS`.

The `windows/` directory is generated by `flutter create` in CI, so we inject
the macro at build time (idempotent, ASCII-only output so it works on a
Windows console with a non-UTF8 code page).

Usage:
    python3 tool/inject_windows_cmake.py [--root .]
"""
import argparse
import os
import sys

MARKER = '_SILENCE_EXPERIMENTAL_COROUTINE_DEPRECATION_WARNINGS'
CANDIDATES = ['windows/CMakeLists.txt']


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--root', default='.')
    args = parser.parse_args()

    path = None
    for rel in CANDIDATES:
        candidate = os.path.join(args.root, rel)
        if os.path.exists(candidate):
            path = candidate
            break
    if path is None:
        print('[skip] windows/CMakeLists.txt not found')
        return 0

    text = open(path, encoding='utf-8').read()
    if MARKER in text:
        print('[exists] compatibility macro already injected')
        return 0

    lines = text.splitlines(keepends=True)
    insert_at = None
    for i, line in enumerate(lines):
        if line.lstrip().startswith('project('):
            insert_at = i + 1
            break
    if insert_at is None:
        print('[fail] no project(...) line found in %s' % path)
        return 1

    injection = (
        '# OGL: permission_handler_windows uses legacy <experimental/coroutine>,\n'
        '# which new MSVC rejects; define this macro to silence it (build-time).\n'
        'add_compile_definitions(%s)\n' % MARKER
    )
    lines.insert(insert_at, injection)
    open(path, 'w', encoding='utf-8').write(''.join(lines))

    if MARKER not in open(path, encoding='utf-8').read():
        print('[fail] macro not present after injection')
        return 1
    print('[inject] macro injected into %s' % path)
    print('[ok] windows compatibility macro in place')
    return 0


if __name__ == '__main__':
    sys.exit(main())